# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 476a6763fb6b4a1fa48dcf440062877994dea0bd92186732ad0312a36883fae664dc05a8cd4a7c0df8fa1ecc6c64d51a1bed0e1973220ce3e92169944a21389f

test:
  secret_key_base: 04f6c20257b6186f7235c408ef656a692277d8b2e6ec690fbf25f4314320e7719ec27120c9c887418845fff1be74c3e8a65d2cf96d954af875ab46168186d254

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
